.dashJs9_js_metadata <- function() {
deps_metadata <- list(`dash_js9` = structure(list(name = "dash_js9",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'third_party/js9prefs.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashJs9",
all_files = FALSE), class = "html_dependency"),
`dash_js9` = structure(list(name = "dash_js9",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'third_party/js9.min.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashJs9",
all_files = FALSE), class = "html_dependency"),
`dash_js9` = structure(list(name = "dash_js9",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'third_party/js9plugins.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashJs9",
all_files = FALSE), class = "html_dependency"),
`dash_js9` = structure(list(name = "dash_js9",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_js9.min.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashJs9",
all_files = FALSE), class = "html_dependency"),
`dash_js9` = structure(list(name = "dash_js9",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_js9.min.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashJs9",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_js9` = structure(list(name = "dash_js9",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = NULL,
stylesheet = 'third_party/js9.css', head = NULL, attachment = NULL, package = "dashJs9",
all_files = FALSE), class = "html_dependency"),
`dash_js9` = structure(list(name = "dash_js9",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = NULL,
stylesheet = 'third_party/js9support.css', head = NULL, attachment = NULL, package = "dashJs9",
all_files = FALSE), class = "html_dependency"))
return(deps_metadata)
}
